service:
  type: LoadBalancer

ingress:
  enabled: true
  hosts:
    - host: apisix-172.18.0.2.nip.io
      paths: ["/"]

metrics:
  serviceMonitor:
    enabled: false

etcd:  # we use yaml as config_provider, so etcd not needed. it is for config from ui
  enabled: true

apisix:
  admin:
    enabled: true
    enable_admin_ui: true
    credentials:
      admin: edd1c9f034335f136f87ad84b625c8f1
      viewer: 4054f7cf07e344346cd3f287985e76a2
      secretName: ""
      secretAdminKey: ""  # the default key name "admin"
      secretViewerKey: ""  # default key name "viewer"
    allow:
      ipList:
        - 0.0.0.0/0
    ingress:
      enabled: true
      hosts:
        - host: apisix-admin-172.18.0.2.nip.io
          paths: ["/apisix"]
  # https://apisix.apache.org/docs/apisix/deployment-modes/
  deployment:
    mode: traditional
    role: "traditional"
    role_traditional:
      config_provider: "etcd"  # yaml, etcd

# Recomended to install ingress controller from separate chart
# ingress-controller:
#   enabled: true
#   gatewayProxy:
#     createDefault: true
#   config:
#     logLevel: "info"  # info, debug
#     kubernetes:
#       defaultIngressClass: true
#     provider:
#       initSyncDelay: "1m"  # for test to see changes in routes quickly
